// 星獸偵探社的劇本。每一集有 5 個線索單字，解開單字才會取得線索文字；
// 五條線索合起來，剛好只留下三位嫌疑星獸中的一位。
// clue.word 必須存在於該側的單字庫（姊姊 data/vocabulary-jie.json，妹妹 data/vocabulary.json）。

export const DETECTIVE_CONFIGS = {
  sister: {
    profileKey: 'jie',
    eyebrow: 'THE AZURE CASEBOOK',
    title: '星獸偵探社',
    subtitle: '蒼藍檔案',
    detective: '蒼藍偵探・姊姊',
    partner: 'sparkit',
    intro: '星獸偵探社收到了四件委託。到現場點開每一個線索，用動作、食物、校園與生活單字解開它，再從三位嫌疑星獸中指認出真正的答案。',
    ink: '#12294a',
    paper: '#f4f0e4',
    accent: '#c9a227',
    tint: '#2f6d8f',
    cases: [
      {
        id: 'jie-1',
        title: '消失的巧克力',
        en: 'THE MISSING CHOCOLATE',
        icon: '🍫',
        place: '月光小學・餐廳',
        client: '委託人：三年二班的值日生',
        brief: '午餐後要發給全班的巧克力點心不見了。餐廳的門一直有人看著，代表偷點心的星獸還在這間餐廳裡。',
        clues: [
          { word: 'chocolate', kind: 'choose-en', spot: '空的包裝紙', finding: '桌上只剩下一張空包裝紙，舔得乾乾淨淨——犯人最愛甜的東西。' },
          { word: 'carrot', kind: 'listen', spot: '被啃過的蔬菜', finding: '地板上有一小截被啃過的胡蘿蔔——犯人也吃蔬菜。' },
          { word: 'chicken', kind: 'choose-zh', spot: '沒動過的三明治', finding: '雞肉三明治一口都沒被碰過——犯人不吃肉。' },
          { word: 'crisps', kind: 'spell', spot: '打開的洋芋片袋', finding: '洋芋片的袋子被打開了，卻一片都沒少——犯人不愛鹹的。' },
          { word: 'coconut', kind: 'cloze', spot: '窗台上的椰子殼', finding: '窗台上有半顆椰子殼，裡面塞滿了新鮮的葉子——犯人來自森林。', sentence: 'Half a ____ shell is on the window.' },
        ],
        question: '拿走巧克力的星獸是誰？',
        suspects: [
          { beast: 'coalpup', profile: '焰羽系。最喜歡烤肉，看到雞肉三明治一定會先吃掉。' },
          { beast: 'fernhorn', profile: '森芽系。只吃甜點和蔬菜，鹿角上總是長著新鮮的葉子。' },
          { beast: 'pearlray', profile: '潮汐系。只吃海裡的食物，離開水面就沒有力氣。' },
        ],
        culprit: 'fernhorn',
        verdict: '芽角把巧克力藏進椰子殼裡帶走了。牠不是小偷——牠想在班上同學生日那天，給大家一個驚喜。',
      },
      {
        id: 'jie-2',
        title: '教室裡的怪聲',
        en: 'THE CLASSROOM NOISE',
        icon: '🏫',
        place: '月光小學・三年二班教室',
        client: '委託人：留下來打掃的班長',
        brief: '每天放學後，鎖著的教室裡都會傳出聲音。隔天早上進教室，東西卻總是比前一天更整齊。',
        clues: [
          { word: 'classroom', kind: 'choose-en', spot: '上鎖的教室門', finding: '門窗全都從外面鎖著，只有牆上的插座蓋子被打開——犯人是沿著電線進來的。' },
          { word: 'chair', kind: 'spell', spot: '被搬動的椅子', finding: '一張椅子被搬到書櫃前面——犯人不會飛，得墊高才搆得到最上層。' },
          { word: 'computer', kind: 'listen', spot: '還亮著的電腦', finding: '電腦螢幕還亮著，鍵盤上有細細的靜電痕跡——犯人身上帶電。' },
          { word: 'class', kind: 'choose-zh', spot: '翻開的班級日誌', finding: '班級日誌被翻到今天這一頁，紙的邊緣像被靜電輕輕吸得捲了起來。' },
          { word: 'classmate', kind: 'cloze', spot: '擺正的同學合照', finding: '同學合照被小心地擺正了——犯人不是在搗亂，是在整理。', sentence: 'Every ____ is smiling in this photo.' },
        ],
        question: '半夜待在教室裡的星獸是誰？',
        suspects: [
          { beast: 'orchidrake', profile: '森芽系。有一對花瓣翅膀，想拿高處的東西時直接飛上去就好。' },
          { beast: 'starstag', profile: '雷光系。沿著電線移動，全身帶著靜電，但是不會飛。' },
          { beast: 'lavahoot', profile: '焰羽系。會飛，羽毛帶著火星，碰過的紙都會留下焦痕。' },
        ],
        culprit: 'starstag',
        verdict: '星角每天晚上順著電線溜進教室，把桌椅和照片一一擺好。牠說：整理好了，就像也是這個班級的一員了。',
      },
      {
        id: 'jie-3',
        title: '被打斷的排練',
        en: 'THE INTERRUPTED REHEARSAL',
        icon: '🎭',
        place: '活動中心・舞台',
        client: '委託人：話劇社的社長',
        brief: '排練到一半，舞台的燈忽然暗了。等燈再亮起來，道具都被排得整整齊齊，布幕後面卻傳出小小的哭聲。',
        clues: [
          { word: 'dance', kind: 'listen', spot: '地板上的腳印', finding: '舞台地板上留下一圈圈旋轉的腳印——犯人踩在地上跳了舞。' },
          { word: 'clap', kind: 'choose-en', spot: '牆上的手印', finding: '牆上有一雙小小的、成對的手印——犯人有手掌，而且會拍手。' },
          { word: 'cry', kind: 'choose-zh', spot: '沒乾的水痕', finding: '布幕後面有一小攤還沒乾的淚痕——犯人身上有水氣。' },
          { word: 'read', kind: 'cloze', spot: '翻皺的劇本', finding: '攤開的劇本被翻到主角那一幕，邊角都翻皺了。', sentence: 'Someone tried to ____ the script here.' },
          { word: 'catch', kind: 'spell', spot: '接住的道具球', finding: '從架上掉下來的道具球被穩穩接住，還放了回去——犯人有手，接得住東西。' },
        ],
        question: '躲在布幕後面的星獸是誰？',
        suspects: [
          { beast: 'coralisk', profile: '潮汐系。有一雙小手掌，走過的地方會留下水痕。' },
          { beast: 'flarebeetle', profile: '焰羽系。前腳是硬硬的甲殼，沒有手掌，抓不住球。' },
          { beast: 'cloudrake', profile: '雷光系。永遠飄在半空中，腳從來不落地。' },
        ],
        culprit: 'coralisk',
        verdict: '珊角躲在布幕後面偷偷跟著排練學跳舞，被發現的時候太緊張就哭了。社長邀請牠一起上台——這次牠笑著點了頭。',
      },
      {
        id: 'jie-4',
        title: '星語鐘塔的最後謎題',
        en: 'THE CLOCKTOWER FINALE',
        icon: '🕰️',
        place: '星語鐘塔',
        client: '委託人：鐘塔的守塔人',
        brief: '畢業典禮前一週，沒有人進得去的鐘塔每天早上都變得更乾淨。守塔人把最後一件委託交給了偵探社。',
        clues: [
          { word: 'clothes', kind: 'choose-en', spot: '樓梯上的小披風', finding: '鐘塔樓梯上掉了一件小小的披風——尺寸不比小孩子大。' },
          { word: 'color', kind: 'choose-zh', spot: '披風上的粉末', finding: '披風上沾著三種顏色的光粉：紅色、藍色和金色。' },
          { word: 'clean', kind: 'spell', spot: '擦得發亮的地板', finding: '整座鐘塔被擦得一塵不染，連最高的鐘面都亮晶晶。' },
          { word: 'closed', kind: 'listen', spot: '從裡面上鎖的門', finding: '大門是從裡面鎖上的，門上掛著一張手寫的「今日打烊」。' },
          { word: 'child', kind: 'cloze', spot: '地上的小腳印', finding: '地上留著一排腳印，比姊姊的手掌還小，而且一路走到鐘面前。', sentence: 'These footprints belong to a small ____.' },
        ],
        question: '每天把鐘塔打掃乾淨的星獸是誰？',
        suspects: [
          { beast: 'phoenixel', profile: '焰羽系。晨光羽毛會散出紅、藍、金三色的光粉，身高和小孩差不多，最喜歡把東西擦到發亮。' },
          { beast: 'moonjelly', profile: '潮汐系。全身透明沒有顏色，飄在半空中，不會留下腳印。' },
          { beast: 'mycomole', profile: '森芽系。走過的路都會留下一整排灰灰的孢子。' },
        ],
        culprit: 'phoenixel',
        verdict: '晨羽趁著沒人的清晨爬上鐘塔，一階一階把它擦亮。牠希望姊姊的畢業典禮，能在全星語大陸最漂亮的鐘塔上舉行。',
      },
    ],
  },

  younger: {
    profileKey: 'mei',
    eyebrow: 'THE SUNBEAM CASEBOOK',
    title: '星獸偵探社',
    subtitle: '曙光檔案',
    detective: '曙光偵探・妹妹',
    partner: 'sparkit',
    intro: '彩虹王國發生了四件小事件。到現場點一點每一個線索，把英文單字答對就能看到線索，最後從三隻星獸裡找出答案！',
    ink: '#1d3b52',
    paper: '#fff6e4',
    accent: '#ffb648',
    tint: '#3fa9a0',
    cases: [
      {
        id: 'mei-1',
        title: '不見的彩虹風箏',
        en: 'THE MISSING KITE',
        icon: '🪁',
        place: '彩虹公園',
        client: '委託人：在公園放風箏的小男孩',
        brief: '風箏線斷掉了，風箏一下子就不見了。公園裡的三隻星獸，只有一隻有可能把風箏帶走。',
        clues: [
          { word: 'kite', kind: 'choose-en', spot: '斷掉的風箏線', finding: '風箏線斷在長椅旁邊，風箏卻不見了。' },
          { word: 'cloud', kind: 'listen', spot: '形狀怪怪的雲', finding: '天空有一朵雲的形狀怪怪的，好像裡面藏了東西——犯人飛得到雲那麼高。' },
          { word: 'flower', kind: 'choose-zh', spot: '被壓到的花', finding: '地上的花被壓出一個圓圓的凹痕，犯人在這裡停過。' },
          { word: 'umbrella', kind: 'cloze', spot: '忘記帶走的雨傘', finding: '有人急急忙忙走掉，把雨傘留在原地忘了帶。', sentence: 'I have an ____ in my hand.' },
          { word: 'bench', kind: 'spell', spot: '長椅上的花瓣', finding: '長椅上留下一片閃亮亮的花瓣——犯人身上會掉花瓣。' },
        ],
        question: '把風箏帶走的星獸是誰？',
        suspects: [
          { beast: 'orchidrake', profile: '有一對花瓣翅膀，可以飛到雲上面。' },
          { beast: 'mosscub', profile: '背著厚厚的苔蘚殼，只能在地上慢慢走。' },
          { beast: 'tidekip', profile: '一直待在水裡，離開水就動不了。' },
        ],
        culprit: 'orchidrake',
        verdict: '蘭翼把風箏帶到雲的上面去了。牠說：這個風箏那麼漂亮，我想讓它飛得比誰都高！',
      },
      {
        id: 'mei-2',
        title: '動物園的悄悄話',
        en: 'THE ZOO WHISPERS',
        icon: '🦁',
        place: '彩虹動物園',
        client: '委託人：動物園的管理員',
        brief: '每天晚上，動物園裡都會傳出好聽的歌聲。早上大家醒來，鳥巢裡還會多出一顆亮晶晶的珠子。',
        clues: [
          { word: 'monkey', kind: 'choose-en', spot: '一直笑的猴子', finding: '猴子指著樹上一直笑，好像昨天晚上很開心。' },
          { word: 'duck', kind: 'spell', spot: '池塘邊的腳印', finding: '池塘邊有一排濕濕的腳印，從水裡走向樹叢——犯人從水裡來。' },
          { word: 'snake', kind: 'choose-zh', spot: '沒睡著的蛇', finding: '蛇說牠昨天晚上聽到有人在唱歌，唱得很好聽。' },
          { word: 'bird', kind: 'listen', spot: '鳥巢裡的珠子', finding: '鳥巢裡多了一顆亮晶晶的珠子，不是鳥蛋——犯人身上會掉珍珠。' },
          { word: 'bear', kind: 'cloze', spot: '打開的蜂蜜罐', finding: '熊的蜂蜜罐被打開了，蜂蜜卻一滴都沒少——犯人沒有偷吃。', sentence: 'The ____ has a honey pot.' },
        ],
        question: '晚上在動物園唱歌的星獸是誰？',
        suspects: [
          { beast: 'pearlray', profile: '住在水裡，唱歌很好聽，身上會掉下小珍珠。' },
          { beast: 'sunroar', profile: '聲音很大很吵，而且最愛偷吃甜甜的蜂蜜。' },
          { beast: 'acornyx', profile: '住在樹上，喜歡把橡實一顆一顆收集起來藏好。' },
        ],
        culprit: 'pearlray',
        verdict: '珠翼每天晚上從池塘上岸，唱歌給睡不著的動物聽，還留下一顆珍珠當作謝禮。現在牠變成動物園的晚安歌手了。',
      },
      {
        id: 'mei-3',
        title: '音樂會走音之謎',
        en: 'THE OFF-KEY CONCERT',
        icon: '🎻',
        place: '玩具音樂廳',
        client: '委託人：音樂會的小提琴手',
        brief: '音樂會前一天晚上，燈全部暗掉了。燈亮起來以後，小提琴的聲音就變得怪怪的。',
        clues: [
          { word: 'violin', kind: 'listen', spot: '走音的小提琴', finding: '小提琴上有一根弦是全新的，跟其他的弦不一樣，所以聲音才會怪怪的。' },
          { word: 'piano', kind: 'spell', spot: '琴鍵上的腳印', finding: '鋼琴的琴鍵上有一個小小的腳印，摸起來還暖暖的——犯人的身體是熱的。' },
          { word: 'train', kind: 'choose-en', spot: '自己開走的火車', finding: '玩具火車自己開到舞台中間才停下來，好像有人搭著它過來。' },
          { word: 'dancer', kind: 'choose-zh', spot: '舞者看到的光', finding: '舞者說，燈暗掉的時候有東西發出橘色的光——犯人身上會發光。' },
          { word: 'doctor', kind: 'cloze', spot: '醫生的檢查報告', finding: '醫生檢查完說：這根弦不是被弄斷的，是被人「換上去」的。', sentence: 'The ____ checks the violin.' },
        ],
        question: '晚上偷偷碰小提琴的星獸是誰？',
        suspects: [
          { beast: 'cinnamink', profile: '身體暖暖的，走路的時候會發出橘色的光。' },
          { beast: 'frostfin', profile: '身體冰冰的，碰過的東西都會結上一層霜。' },
          { beast: 'cedaroo', profile: '全身是綠色的，不會發光，走路完全沒有聲音。' },
        ],
        culprit: 'cinnamink',
        verdict: '桂火發現小提琴的弦快要斷了，就趁晚上偷偷幫忙換上新的弦，只是還來不及把音調準。音樂會最後順利開演了。',
      },
      {
        id: 'mei-4',
        title: '數字城堡的暗號',
        en: 'THE NUMBER CASTLE CODE',
        icon: '🏰',
        place: '數字城堡',
        client: '委託人：城堡的門衛',
        brief: '每天早上，城堡的牆上都會多出新的小手印。門衛數了數，剛好十個，排成整整齊齊的一排。',
        clues: [
          { word: 'three', kind: 'choose-en', spot: '大門上的星星', finding: '城堡大門上刻著三顆星星，有人用手指把它們一顆一顆數過。' },
          { word: 'seven', kind: 'listen', spot: '被踩亮的階梯', finding: '樓梯剛好有七階，每一階都被踩得亮亮的——犯人一階一階走上去，沒有用飛的。' },
          { word: 'ten', kind: 'choose-zh', spot: '牆上的十個手印', finding: '牆上有十個小手印，排成一排，像在數數字一樣。' },
          { word: 'hand', kind: 'spell', spot: '手印的形狀', finding: '每一個手印都只有三根指頭——犯人的手是三根指頭的。' },
          { word: 'foot', kind: 'cloze', spot: '地上的腳印', finding: '地上的腳印圓圓的，看不到腳趾——犯人的腳掌是圓的。', sentence: 'This ____ print is round.' },
        ],
        question: '在城堡裡數數字的星獸是誰？',
        suspects: [
          { beast: 'zappuff', profile: '圓圓的腳掌，手上有三根指頭，只能一階一階慢慢走。' },
          { beast: 'shellark', profile: '尖尖的鳥爪，有四根腳趾，而且會飛。' },
          { beast: 'bloomtoad', profile: '腳掌上有蹼，走過的地方都會留下一灘水。' },
        ],
        culprit: 'zappuff',
        verdict: '電絨每天早上到城堡練習數數字，從一數到十，每數一個就在牆上按一個手印。牠現在已經會從一數到十了！',
      },
    ],
  },
};

export const CLUE_KINDS = ['choose-en', 'choose-zh', 'listen', 'spell', 'cloze'];
